### ISSUE TITLE
translation from client-side controller

### ISSUE THREAD

**Issue by ghost** [juxtapos/Rain#18]
Rain needs some sort of API for i18n (gettext, getmedia...) that could be called from js.

**Comment by MitkoTschimev** [comment]
Yes that's a good idea. I will look how i can include it ;)

Thanks for this idea

**Comment by juxtapos** [comment]
we have this already in place, check out the translation_example component.

## 

Claus Augusti
Division Frontend Architect
1&1 Development Hosting

Phone: +49 (721) 91374 - 4172
Mobile: +49 (178) 233 58 59
claus.augusti@1und1.de

1&1 Internet AG
Ernst-Frey-Str. 9
76135 Karlsruhe, Germany

Vorstand: Henning Ahlert, Ralph Dommermuth, Matthias Ehrlich, Robert Hoffmann, Markus Huhn, Hans-Henning Kettler, Dr. Oliver Mauss, Jan Oetjen
Aufsichtsratsvorsitzender: Michael Scheeren

Amtsgericht Montabaur / HRB 6484

Am 30.09.2011 um 10:00 schrieb georgecocu reply@reply.github.com:

**Comment by MitkoTschimev** [comment]
Have you done something Juxtapos? Or have i misunderstood it george :)?
You need an API directly from JS and not only parsed text. Is that right?

**Comment by ghost** [comment]
gettext() is only parsed on the server side and it's not a callable function from the client side controllers. This is needed, for example, for i18n of the error messages.

**Comment by MitkoTschimev** [comment]
Yes so i have understand it correctly ;)
I will implement it ;)
